DROP TABLE IF EXISTS users;

CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  username VARCHAR(50) NOT NULL,
  password VARCHAR(50) NOT NULL,
  task VARCHAR(50),
  date DATE NOT NULL,
  status VARCHAR(50) NOT NULL
);

SELECT * FROM users;